"""Regenerate the stale dataset figures from post-trim .pt data.

Outputs (all post-trim):
- figures/contact_intensity_full.png  (hero)
- figures/contact_intensity_20min.png (zoom)
- figures/dataset_figures/F1_episode_length_histogram.png
- figures/dataset_figures/F2_contact_event_duration_histogram.png
- figures/dataset_figures/F8_per_episode_summary.png + .csv

Skipping F3 (heatmap) / F4 (montage) / F5 (3D trajectory) / F6 (correlation) /
F7 (comparison table) — they don't change qualitatively after a 17-min trim
and would need to be regenerated by the original (unsaved) plotting code.

Also updates figures/dataset_figures/freeze_diagnose/summary.json with
trimmed-coord events (#6).
"""

# This is a top-level script (no main() function — all logic runs at
# module load). Refuse to act when imported to keep import-time tests safe.
if __name__ != "__main__":
    raise ImportError(
        f"{__name__!r} is a one-shot script and should be run via "
        f"\"python scripts/{__file__.split(chr(47))[-1]}\""
    )
import csv
import json
import os
import gc
from pathlib import Path
import urllib.request

os.environ.setdefault("HF_HUB_ENABLE_HF_TRANSFER", "1")

import numpy as np
import torch
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

PT_ROOT = Path("/media/yxma/Disk1/twm/processed/mode1_v1/motherboard")
OUT = Path("/tmp/aud_figs")
OUT.mkdir(parents=True, exist_ok=True)

TACTILE_THRESHOLD = 0.4  # mixed metric default

# ── Load per-episode data we need ──────────────────────────────────────────
per_ep = []   # list of {ep, T, dur_s, mL, mR, intensity_max}
for pt in sorted(PT_ROOT.rglob("episode_*.pt")):
    date = pt.parent.name
    if date == "2026-03-23":
        continue
    ep_key = f"{date}/{pt.stem}"
    print(f"loading {ep_key}...")
    d = torch.load(pt, weights_only=False, map_location="cpu")
    T = d["view"].shape[0]
    per_ep.append({
        "ep_key": ep_key,
        "T": T,
        "dur_s": T / 30.0,
        "iL": d["tactile_left_intensity"].numpy(),
        "iR": d["tactile_right_intensity"].numpy(),
        "mL": d["tactile_left_mixed"].numpy(),
        "mR": d["tactile_right_mixed"].numpy(),
        "pL": d["sensor_left_pose"][:, :3].numpy(),
        "pR": d["sensor_right_pose"][:, :3].numpy(),
    })
    del d; gc.collect()

# ── F1: episode length histogram ────────────────────────────────────────────
durs_min = np.array([e["dur_s"] / 60 for e in per_ep])
plt.figure(figsize=(8, 4.5))
plt.hist(durs_min, bins=15, color="#0072B2", edgecolor="white")
plt.xlabel("Episode duration (min)")
plt.ylabel("Episode count")
plt.title(f"Episode length distribution — {len(per_ep)} episodes, total {durs_min.sum():.1f} min")
plt.axvline(np.median(durs_min), ls="--", color="#E69F00", label=f"median = {np.median(durs_min):.1f} min")
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig(OUT / "F1_episode_length_histogram.png", dpi=110)
plt.close()
print("F1 done")

# ── F2: contact event duration histogram (events = contiguous runs where
# either-sensor mixed metric > threshold) ──────────────────────────────────
events_s = []
for e in per_ep:
    contact = (e["mL"] > TACTILE_THRESHOLD) | (e["mR"] > TACTILE_THRESHOLD)
    # Find contiguous True runs
    d = np.diff(np.concatenate([[0], contact.astype(int), [0]]))
    starts = np.where(d == 1)[0]
    ends = np.where(d == -1)[0]
    lengths = ends - starts
    events_s.extend((lengths / 30.0).tolist())
events_s = np.array(events_s)
plt.figure(figsize=(8, 4.5))
plt.hist(np.clip(events_s, 0, 10), bins=40, color="#0072B2", edgecolor="white")
plt.yscale("log")
plt.xlabel("Contact event duration (s, clipped at 10s)")
plt.ylabel("Event count (log scale)")
plt.title(f"Contact event durations — {len(events_s):,} events, median {np.median(events_s):.2f} s, max {events_s.max():.1f} s")
plt.axvline(np.median(events_s), ls="--", color="#E69F00", label=f"median = {np.median(events_s):.2f} s")
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig(OUT / "F2_contact_event_duration_histogram.png", dpi=110)
plt.close()
print(f"F2 done — {len(events_s)} contact events post-trim (median {np.median(events_s):.2f}s)")

# ── F8: per-episode summary CSV + PNG ─────────────────────────────────────
import io
rows = []
for e in per_ep:
    contact = (e["mL"] > TACTILE_THRESHOLD) | (e["mR"] > TACTILE_THRESHOLD)
    contact_pct = 100.0 * contact.mean()
    date, ep_stem = e["ep_key"].split("/")
    rows.append({
        "Date": date,
        "Episode": ep_stem,
        "Frames": e["T"],
        "Dur (s)": round(e["dur_s"], 1),
        "Contact %": round(contact_pct, 1),
        "Max I_L": round(float(e["iL"].max()), 2),
        "Max I_R": round(float(e["iR"].max()), 2),
        "L drift?": "—",
        "R drift?": "—",
    })
with open(OUT / "F8_per_episode_summary.csv", "w", newline="") as f:
    w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
    w.writeheader()
    w.writerows(rows)

# F8 PNG: render as a styled table
import matplotlib.patches as mpatches
fig, ax = plt.subplots(figsize=(11, max(4, 0.25 * (len(rows) + 2))))
ax.axis("off")
cell_text = [[str(r[k]) for k in rows[0].keys()] for r in rows]
col_labels = list(rows[0].keys())
tbl = ax.table(cellText=cell_text, colLabels=col_labels, loc="center", cellLoc="center")
tbl.auto_set_font_size(False)
tbl.set_fontsize(8)
tbl.scale(1, 1.4)
plt.title(f"Per-episode summary — {len(per_ep)} files, total {sum(r['Frames'] for r in rows):,} frames, "
          f"{sum(r['Dur (s)'] for r in rows)/60:.1f} min")
plt.tight_layout()
plt.savefig(OUT / "F8_per_episode_summary.png", dpi=110, bbox_inches="tight")
plt.close()
print("F8 done")

# ── Hero: contact_intensity_full.png + contact_intensity_20min.png ────────
# Audio-waveform-style: time on x-axis, left intensity above, right mirrored below.
ts_all_L = []; ts_all_R = []; offset = 0.0
boundaries = []
for e in per_ep:
    ts = offset + np.arange(e["T"]) / 30.0
    ts_all_L.append((ts, e["mL"]))
    ts_all_R.append((ts, e["mR"]))
    boundaries.append((offset, offset + e["dur_s"], e["ep_key"]))
    offset += e["dur_s"]

fig, ax = plt.subplots(figsize=(16, 4))
for ts, m in ts_all_L:
    ax.fill_between(ts, 0, m, color="#E69F00", alpha=0.6, linewidth=0)
for ts, m in ts_all_R:
    ax.fill_between(ts, 0, -m, color="#0072B2", alpha=0.6, linewidth=0)
for x0, x1, _ in boundaries:
    ax.axvline(x1, color="gray", lw=0.3, alpha=0.5)
ax.set_xlabel("Time across all recordings (s)")
ax.set_ylabel("Tactile mixed metric  (L ▲ orange · R ▼ blue)")
ax.set_title(f"React — tactile contact timeline, all {len(per_ep)} episodes, {offset/60:.1f} min total (post-trim)")
ax.grid(alpha=0.3)
plt.tight_layout()
plt.savefig(OUT / "contact_intensity_full.png", dpi=110)
plt.close()

# 20-minute zoom (skip first 5 min where things are usually warmups)
fig, ax = plt.subplots(figsize=(16, 4))
zoom_start, zoom_end = 5 * 60, 25 * 60
for ts, m in ts_all_L:
    mask = (ts >= zoom_start) & (ts <= zoom_end)
    ax.fill_between(ts[mask], 0, m[mask], color="#E69F00", alpha=0.7, linewidth=0)
for ts, m in ts_all_R:
    mask = (ts >= zoom_start) & (ts <= zoom_end)
    ax.fill_between(ts[mask], 0, -m[mask], color="#0072B2", alpha=0.7, linewidth=0)
for x0, x1, key in boundaries:
    if zoom_start <= x1 <= zoom_end:
        ax.axvline(x1, color="gray", lw=0.4, alpha=0.5)
        ax.text(x1, ax.get_ylim()[1] * 0.95, key.split("/")[-1].replace("episode_", "ep"),
                rotation=90, fontsize=6, va="top", ha="right", color="gray")
ax.set_xlim(zoom_start, zoom_end)
ax.set_xlabel("Time (s)")
ax.set_ylabel("Tactile mixed metric  (L ▲ orange · R ▼ blue)")
ax.set_title("React — 20-minute zoom (5-25 min)")
ax.grid(alpha=0.3)
plt.tight_layout()
plt.savefig(OUT / "contact_intensity_20min.png", dpi=110)
plt.close()
print("hero figures done")


# ── #6: freeze_diagnose/summary.json — shift coords to trimmed-pt ─────────
trim_offsets = {
    "2026-05-11/episode_005": 2429,
    "2026-05-11/episode_012": 9719,
    "2026-05-11/episode_017": 19228,
}
existing = json.loads(urllib.request.urlopen(
    "https://huggingface.co/datasets/yxma/React/raw/main/figures/dataset_figures/freeze_diagnose/summary.json"
).read())
new_events = []
for ev in existing.get("events", []):
    off = trim_offsets.get(ev["episode"], 0)
    a = ev["a"] - off; b = ev["b"] - off
    if b < 0:
        continue
    a = max(0, a)
    nev = dict(ev)
    nev["a"], nev["b"] = a, b
    nev["length_s"] = round((b - a + 1) / 30.0, 3)
    new_events.append(nev)
existing["events"] = new_events
existing["counts"]["ot_loss"] = sum(1 for e in new_events if e.get("verdict") in ("ot_loss", "pipeline_stall"))
existing["coordinates"] = "TRIMMED-pt frame indices"
existing["note"] = ("After trim, the long start-of-episode prefixes (ep_005/012/017) "
                    "are removed entirely. What remains is real mid-episode mocap dropout.")
with open(OUT / "freeze_diagnose_summary.json", "w") as f:
    json.dump(existing, f, indent=2)
print(f"freeze_diagnose summary updated: {len(new_events)} events post-trim "
      f"(was {len(existing.get('events', []))} pre-trim)")

# ── Push ────────────────────────────────────────────────────────────────
from huggingface_hub import HfApi, CommitOperationAdd
api = HfApi()
ops = [
    CommitOperationAdd(path_in_repo="figures/contact_intensity_full.png",
                       path_or_fileobj=str(OUT / "contact_intensity_full.png")),
    CommitOperationAdd(path_in_repo="figures/contact_intensity_20min.png",
                       path_or_fileobj=str(OUT / "contact_intensity_20min.png")),
    CommitOperationAdd(path_in_repo="figures/dataset_figures/F1_episode_length_histogram.png",
                       path_or_fileobj=str(OUT / "F1_episode_length_histogram.png")),
    CommitOperationAdd(path_in_repo="figures/dataset_figures/F2_contact_event_duration_histogram.png",
                       path_or_fileobj=str(OUT / "F2_contact_event_duration_histogram.png")),
    CommitOperationAdd(path_in_repo="figures/dataset_figures/F8_per_episode_summary.png",
                       path_or_fileobj=str(OUT / "F8_per_episode_summary.png")),
    CommitOperationAdd(path_in_repo="figures/dataset_figures/F8_per_episode_summary.csv",
                       path_or_fileobj=str(OUT / "F8_per_episode_summary.csv")),
    CommitOperationAdd(path_in_repo="figures/dataset_figures/freeze_diagnose/summary.json",
                       path_or_fileobj=str(OUT / "freeze_diagnose_summary.json")),
]
api.create_commit(
    repo_id="yxma/React", repo_type="dataset", operations=ops,
    commit_message=(
        "Audit batch 2: regen hero contact_intensity_*.png + F1/F2/F8 + "
        "freeze_diagnose/summary.json with post-trim numbers (#1, #2, #6). "
        "F3/F4/F5/F6/F7 unchanged — qualitatively unaffected by trim."
    ),
)
print("Push done.")
